[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { git = "https://github.com/anza-xyz/compiler-builtins", tag = "solana-tools-v1.43", features = ['rustc-dep-of-std'] }

[build-dependencies]
cc = "1.0.90"
