[package]
name = "profiler_builtins"
version = "0.0.0"
edition = "2021"

[lib]
test = false
bench = false
doc = false

[dependencies]
core = { path = "../core" }
compiler_builtins = { git = "https://github.com/anza-xyz/compiler-builtins", rev = "8e355a96707fd38c430259f18541c210c3495f19", features = ['rustc-dep-of-std'] }

[build-dependencies]
cc = "1.0.90"
